#:import track track

MainWidget:

<ControlButton@Button>:

<MainWidget>:
    tracks_layout: tracks_layout
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            size_hint_y: None
            height: dp(100)
            ControlButton:
                text: "PLAY"
            ControlButton:
                text: "STOP"
        BoxLayout:
            id: tracks_layout
            orientation: "vertical"
